apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://rockdb_prometheus:9090
  isDefault: true
  access: proxy
  editable: true

- name: rockdb_influxdb
  uid: cfca5jww9ysxsa
  type: influxdb
  access: proxy
  url: http://rockdb_influxdb:8086
  basicAuth: true
  jsonData:
    version: Flux
    organization: rockdb
    defaultBucket: timemachine
    httpMode: POST
    tlsSkipVerify: true
  secureJsonData:
    token: rockdb_super_secret_token_change_me
  editable: true